import turtle
t = turtle.Turtle()
x = turtle.Turtle()
x.speed(0)

if False:
    t.speed(0)
    t.color('black')
    t.pensize(5)
    t.left(225)
    t.fillcolor('white')

    t.pu()
    t.goto(30,-210)
    t.right(225)
    t.begin_fill()
    for n in range(2):
        t.pd()
        t.fd(300)
        t.right(90)
        t.fd(110)
        t.right(90)
    t.end_fill()
    t.hideturtle()
    t.pu()
    t.home()
    t.pd()

    t.left(225)
    t.begin_fill()
    t.fd(50)
    t.left(45)
    t.fd(100)
    t.left(45)
    t.fd(200)
    t.circle(10,180)
    t.fd(190)
    t.right(45)
    t.fd(85)
    t.right(45)
    t.fd(43)
    t.circle(10,180)
    t.end_fill()

if False:#灰色背景
    t.hideturtle()
    x.pu()
    x.shape('turtle')
    x.goto(-500,500)
    x.color('lightgrey')
    x.pd()
    x.begin_fill()
    for n in range(4):
        x.fd(1000)
        x.right(90)
    x.end_fill()

if False:#转花
    x.pu()
    x.goto(0,50)

    for n in range(3):
        x.color('lightgrey')
        x.begin_fill()
        x.pd()
        x.circle(50,90)
        x.fd(200)
        x.circle(50,180)
        x.fd(200)
        x.circle(50,90)
        x.end_fill()
        x.pu()
        x.left(90)
        x.fd(50)
        x.color('red')
        x.dot(70)
        x.fd(100)
        x.dot(70)
        x.fd(100)
        x.color('grey')
        x.dot(95)
        x.fd(-250)
        x.right(90)
        x.pu()
        x.circle(-100,120)
    x.color('yellow')
    x.goto(0,-50)
    x.dot(120)

if False:#格
    x.fillcolor('snow')
    x.pensize(3)
    x.begin_fill()
    for n in range(4):
        x.fd(15)
        x.right(90)
    x.end_fill()
    x.pu()
    x.right(90)
    x.fd(7)
    x.left(90)
    x.fd(7)
    x.color('black')
    x.dot(8)

if True:
    t.pu()
    t.write('转花推块',font = 30)
t.hideturtle()
x.hideturtle()
